return {
	"xiyaowong/transparent.nvim",
	config = function()
		local transparent = require("transparent")
		-- transparent.clear_prefix("lualine")
		transparent.setup({
			lualine_style = "powerlevel",
			exclude_groups = {
				"StatusLine",
				"StatusLineNC",
				"LualineNormal",
				"LualineInsert",
				"LualineVisual",
				"LualineReplace",
				"LualineCommand",
				"LualineInactive",
				"LualineNormalNC",
				"LualineInsertNC",
				"LualineVisualNC",
				"LualineReplaceNC",
				"LualineCommandNC",
				"LualineInactiveNC",
			},
			extra_groups = {
				"NeoTreeCursorLine",
				"NeoTreeDimText",
				"NeoTreeDirectoryIcon",
				"NeoTreeDirectoryName",
				"NeoTreeDotfile",
				"NeoTreeFileIcon",
				"NeoTreeFileName",
				"NeoTreeFileNameOpene",
				"NeoTreeFilterTerm",
				"NeoTreeFloatBorder",
				"NeoTreeFloatTitle",
				"NeoTreeTitleBar",
				"NeoTreeGitAdded",
				"NeoTreeGitConflict",
				"NeoTreeGitDeleted",
				"NeoTreeGitIgnored",
				"NeoTreeGitModified",
				"NeoTreeGitUnstaged",
				"NeoTreeGitUntracke",
				"NeoTreeGitStaged",
				"NeoTreeHiddenByName",
				"NeoTreeIndentMarker",
				"NeoTreeExpander",
				"NeoTreeNormal",
				"NeoTreeNormalNC",
				"NeoTreeSignColumn",
				"NeoTreeStatusLine",
				"NeoTreeStatusLineNC",
				"NeoTreeVertSplit",
				"NeoTreeWinSeparator",
				"NeoTreeEndOfBuffer",
				"NeoTreeRootName",
				"NeoTreeSymbolicLinkTarget",
				"NeoTreeTitleBar",
				"NeoTreeWindowsHidden",
			},
		})
	end,
}
