return {
	"zaldih/themery.nvim",
	priority = 1000,
	lazy = false,

	config = function()
		require("themery").setup({
			themes = {
				{ name = "Ayu Dark", colorscheme = "ayu-dark" },
				{ name = "Ayu Light", colorscheme = "ayu-light" },
				{ name = "Ayu Mirage", colorscheme = "ayu-mirage" },
				{ name = "CarbonFox", colorscheme = "carbonfox" },
				{ name = "Catppuccin Frappe", colorscheme = "catppuccin-frappe" },
				{ name = "Catppuccin Latte", colorscheme = "catppuccin-latte" },
				{ name = "Catppuccin Macchiato", colorscheme = "catppuccin-macchiato" },
				{ name = "Catppuccin Mocha", colorscheme = "catppuccin-mocha" },
				{ name = "DawnFox", colorscheme = "dawnfox" },
				{ name = "DayFox", colorscheme = "dayfox" },
				{ name = "Decay Dark", colorscheme = "decay-dark" },
				{ name = "Decay Light", colorscheme = "decay-light" },
				{ name = "Decay", colorscheme = "decay-default" },
				{ name = "Decayce", colorscheme = "decayce" },
				{ name = "Dracula", colorscheme = "dracula" },
				{ name = "Duotone Earth Dark", colorscheme = "base2tone_earth_dark" },
				{ name = "Duotone Forest Dark", colorscheme = "base2tone_forest_dark" },
				{ name = "Duotone Sea Dark", colorscheme = "base2tone_sea_dark" },
				{ name = "Duotone Space Dark", colorscheme = "base2tone_space_dark" },
				{ name = "DuskFox", colorscheme = "duskfox" },
				{ name = "Everblush", colorscheme = "everblush" },
				{ name = "Everforest", colorscheme = "everforest" },
				{ name = "Gruvbox", colorscheme = "gruvbox" },
				{ name = "Kanagawa Dragon", colorscheme = "kanagawa-dragon" },
				{ name = "Kanagawa Lotus", colorscheme = "kanagawa-lotus" },
				{ name = "Kanagawa Wave", colorscheme = "kanagawa-wave" },
				{ name = "Leaf", colorscheme = "leaf" },
				{ name = "Melange", colorscheme = "melange" },
				{ name = "NightFox", colorscheme = "nightfox" },
				{ name = "Night Owl", colorscheme = "night-owl" },
				{ name = "Nord", colorscheme = "nord" },
				{ name = "NordFox", colorscheme = "nordfox" },
				{ name = "Nordic", colorscheme = "nordic" },
				{ name = "Rose Pine Dawn", colorscheme = "rose-pine-dawn" },
				{ name = "Rose Pine Moon", colorscheme = "rose-pine-moon" },
				{ name = "Rose Pine", colorscheme = "rose-pine-main" },
				{ name = "Solarized", colorscheme = "solarized" },
				{ name = "Solarized Osaka", colorscheme = "solarized-osaka" },
				{ name = "Solarized Osaka Day", colorscheme = "solarized-osaka-day" },
				{ name = "Solarized Osaka Moon", colorscheme = "solarized-osaka-moon" },
				{ name = "Solarized Osaka Night", colorscheme = "solarized-osaka-night" },
				{ name = "Solarized Osaka Storm", colorscheme = "solarized-osaka-storm" },
				{ name = "Sonokai", colorscheme = "sonokai" },
				{ name = "TeraFox", colorscheme = "terafox" },
				{ name = "Tokyonight Day", colorscheme = "tokyonight-day" },
				{ name = "Tokyonight Moon", colorscheme = "tokyonight-moon" },
				{ name = "Tokyonight Night", colorscheme = "tokyonight-night" },
				{ name = "Tokyonight Storm", colorscheme = "tokyonight-storm" },
				{ name = "Monkokai Pro", colorscheme = "monokai-pro" },
				{ name = "Monokai Classic", colorscheme = "monokai-pro-classic" },
				{ name = "Monokai Default", colorscheme = "monokai-pro-default" },
				{ name = "Monokai Machine", colorscheme = "monokai-pro-machine" },
				{ name = "Monokai Octagon", colorscheme = "monokai-pro-octagon" },
				{ name = "Monokai Ristretto", colorscheme = "monokai-pro-ristretto" },
				{ name = "Monokai Spectrum", colorscheme = "monokai-pro-spectrum" },
				{ name = "Gruvbox Material", colorscheme = "gruvbox-material" },
			},
			livePreview = true,
		})
	end,
}
